# crates/http/Cargo.toml
[package]
name = "http"
version = "0.1.0"
edition = "2021"

[dependencies]
firewall_core = { path = "../core" }
axum        = { workspace = true }
tokio       = { workspace = true }
anyhow      = { workspace = true }
serde       = { workspace = true }
